#pragma once

#if CONFIG_USE_LVGL
#include <material_symbols.h>
#else
#define MATERIAL_SYMBOLS_WIFI ""
#define MATERIAL_SYMBOLS_WIFI_OFF ""
#define MATERIAL_SYMBOLS_WIFI_1_BAR ""
#define MATERIAL_SYMBOLS_WIFI_2_BAR ""
#define MATERIAL_SYMBOLS_ANDROID_CELL_4_BAR ""
#define MATERIAL_SYMBOLS_ANDROID_CELL_4_BAR_OFF ""
#define MATERIAL_SYMBOLS_SIGNAL_CELLULAR_ALT ""
#define MATERIAL_SYMBOLS_SIGNAL_CELLULAR_ALT_1_BAR ""
#define MATERIAL_SYMBOLS_SIGNAL_CELLULAR_ALT_2_BAR ""
#endif
